### ISSUE TITLE
`!weather` to report weather for the user's location

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#63]
> Taras: !weather
> DuckBot: Taras Town is 15C and rainy. Don't forget your umbrella!
> Dave: !weather
> DuckBot: Dave Region is -30C and snowy. Why do you do this.

We'd need each person's location data. If we can pull that from their discord profile, that'd be best (not sure if discord even stores that info though). Otherwise, we can hard code it. Maybe place it in `.env` to hide it, or in a database.

[OpenWeather](https://openweathermap.org/) is a decent weather provider, but the [Weather Network](https://store.api.pelmorex.com/) also has some api access.

As for the _don't forget your umbrella_, it'd be nice to have a set of phrases to tack on depending on the weather.

**Comment by twentylemon** [comment]
https://openweathermap.org/api
https://pyowm.readthedocs.io/en/latest/v3/code-recipes.html
https://github.com/csparpa/pyowm

**Comment by twentylemon** [comment]
https://geopy.readthedocs.io/en/stable/

**Comment by niladricts** [comment]
We can use the open-weather api. For me it is working in a standalone version while incorporating in the duck boat, no data is shown by the bot.

**Comment by twentylemon** [comment]
> We'd need each person's location data. If we can pull that from their discord profile, that'd be best (not sure if discord even stores that info though). Otherwise, we can hard code it. Maybe place it in `.env` to hide it, or in a database.

If we have a database, we can instead have `!weather set-location <location>` update the default location for that person. If no location is set, `!weather` could either error out saying no location is set, or give weather for some default city, then also tell them to set their location.

**Comment by niladricts** [comment]
@twentylemon I did the weather API implementation using the users current IP location. That location is passed to open weather API and fetch the details. It is working but while pushing in main, CI/CD pipeline is failing as, during the build, it can't able to connect to weather API. It is better to put the IP, API_KEY in the .env file for security reasons but during CI/CD build, it will fail. It is because, in git push, we are not pushing any .env file. So, hard coded is the only option.
